plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.0'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'com.diffplug.spotless' version '8.10.0'
	id 'jvm-test-suite'
}

group = 'com.pokeapi'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

repositories {
	mavenCentral()
}

ext {
	set('springCloudVersion', "2025.1.2")
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-jooq'
//	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	implementation 'org.springframework.boot:spring-boot-starter-restclient'
	implementation 'org.springframework.cloud:spring-cloud-starter-circuitbreaker-resilience4j'
	runtimeOnly 'org.postgresql:postgresql'
	testImplementation 'org.springframework.boot:spring-boot-starter-jooq-test'
//	testImplementation 'org.springframework.boot:spring-boot-starter-security-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
//	testImplementation 'org.springframework.boot:spring-boot-testcontainers'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
	}
}

spotless {
	java {
		palantirJavaFormat()
		removeUnusedImports()
		formatAnnotations()
	}
}

testing {
	suites {
		test {
			useJUnitJupiter()
		}

		integrationTest(JvmTestSuite) {
			useJUnitJupiter()

			dependencies {
				implementation project()
				implementation 'org.springframework.boot:spring-boot-starter-test'
				implementation 'org.springframework.boot:spring-boot-starter-restclient-test'
				implementation 'org.springframework.boot:spring-boot-resttestclient'
				implementation 'org.wiremock:wiremock-jetty12:3.13.2'
			}

			targets {
				all {
					testTask.configure {
						shouldRunAfter(test)
					}
				}
			}
		}
	}
}

// TODO have an extra lock to this workaround
// to avoid transitive dependency conflicts due to wiremock-jetty12
configurations.integrationTestRuntimeClasspath {
	resolutionStrategy.eachDependency { details ->
		if (details.requested.group in ['org.eclipse.jetty', 'org.eclipse.jetty.ee10', 'org.eclipse.jetty.http2', 'org.eclipse.jetty.compression']) {
			details.useVersion('12.1.10')
		}
	}
}

check.dependsOn testing.suites.integrationTest