spring.application.name=poke-api

external-api.base.url=https://pokeapi.co/api/v2/

cors.allowed-origins=http://localhost:5173

spring.datasource.url=jdbc:postgresql://localhost:45432/pokemondb
spring.datasource.username=root
spring.datasource.password=root

spring.flyway.url=jdbc:postgresql://localhost:45432/pokemondb
spring.flyway.user=root
spring.flyway.password=root
