spring.application.name=poke-api

external-api.base.url=https://pokeapi.co/api/v2/

cors.allowed-origins=http://localhost:5173

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:45432/pokemondb}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}
