spring.application.name=poke-api

external-api.base.url=https://pokeapi.co/api/v2/

spring.datasource.url=jdbc:postgresql://localhost:45432/pokemondb
spring.datasource.username=root
spring.datasource.password=root
